# Site configuration Options
title: Armin Hadzic
author: Armin Hadzic
description: Armin Hadzic's personal research website.
github_username: arminHadzic
linkedin_username: armin-hadzic
url: http://www.arminhadzic.com

social:
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=DlDme3IAAAAJ&hl=en&oi=sra'}

# Build Settings
markdown: kramdown
theme: minima
