# Site configuration Options
title: Armin Hadzic
author: Armin Hadzic
e-mail: armin[DOT]hadzic@uky[DOT]edu
description: Armin Hadzic's personal research website.
github_username: arminHadzic
url: http://www.arminhadzic.com

# Build Settings
markdown: kramdown
theme: minima
