# Site configuration Options
title: Armin Hadzic
author: Armin Hadzic
description: Armin Hadzic's personal research website.
github_username: arminHadzic
scholar_username: armin.hadzic.scholar@gmail.com
linkedin_username: armin-hadzic
url: http://www.arminhadzic.com

# Build Settings
markdown: kramdown
theme: minima
